name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install required packages and dependencies
      run: |
        pip install -U pip wheel setuptools
        curl -sSL https://install.python-poetry.org | python3.9 - --preview
        poetry install
    - name: Run flake8 style check
      run: |
        source .venv/bin/activate
        flake8
    - name: Run pytest
      run: |
        source .venv/bin/activate
        pytest
